/* 
 * tweak-api
 *
 * Tweak API to integrate with all the Tweak services.  You can find out more about Tweak      at <a href='https://www.tweak.com'>https://www.tweak.com</a>, #tweak.
 *
 * OpenAPI spec version: 1.0.2-alpha.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TweakApi.Api;
using TweakApi.Model;
using TweakApi.Client;
using System.Reflection;

namespace TweakApi.Test
{
    /// <summary>
    ///  Class for testing Billing
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BillingTests
    {
        // TODO uncomment below to declare an instance variable for Billing
        //private Billing instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Billing
            //instance = new Billing();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Billing
        /// </summary>
        [Test]
        public void BillingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Billing
            //Assert.IsInstanceOfType<Billing> (instance, "variable 'instance' is a Billing");
        }

        /// <summary>
        /// Test the property 'CompanyName'
        /// </summary>
        [Test]
        public void CompanyNameTest()
        {
            // TODO unit test for the property 'CompanyName'
        }
        /// <summary>
        /// Test the property 'CompanyEmail'
        /// </summary>
        [Test]
        public void CompanyEmailTest()
        {
            // TODO unit test for the property 'CompanyEmail'
        }
        /// <summary>
        /// Test the property 'CompanyVat'
        /// </summary>
        [Test]
        public void CompanyVatTest()
        {
            // TODO unit test for the property 'CompanyVat'
        }
        /// <summary>
        /// Test the property 'CompanyCard'
        /// </summary>
        [Test]
        public void CompanyCardTest()
        {
            // TODO unit test for the property 'CompanyCard'
        }
        /// <summary>
        /// Test the property 'Subscription'
        /// </summary>
        [Test]
        public void SubscriptionTest()
        {
            // TODO unit test for the property 'Subscription'
        }
        /// <summary>
        /// Test the property 'Limit'
        /// </summary>
        [Test]
        public void LimitTest()
        {
            // TODO unit test for the property 'Limit'
        }
        /// <summary>
        /// Test the property 'TaxPercent'
        /// </summary>
        [Test]
        public void TaxPercentTest()
        {
            // TODO unit test for the property 'TaxPercent'
        }
        /// <summary>
        /// Test the property 'StripeCustomerId'
        /// </summary>
        [Test]
        public void StripeCustomerIdTest()
        {
            // TODO unit test for the property 'StripeCustomerId'
        }
        /// <summary>
        /// Test the property 'StripeCardId'
        /// </summary>
        [Test]
        public void StripeCardIdTest()
        {
            // TODO unit test for the property 'StripeCardId'
        }
        /// <summary>
        /// Test the property 'StripeSubscriptionId'
        /// </summary>
        [Test]
        public void StripeSubscriptionIdTest()
        {
            // TODO unit test for the property 'StripeSubscriptionId'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'TeamId'
        /// </summary>
        [Test]
        public void TeamIdTest()
        {
            // TODO unit test for the property 'TeamId'
        }
        /// <summary>
        /// Test the property 'Team'
        /// </summary>
        [Test]
        public void TeamTest()
        {
            // TODO unit test for the property 'Team'
        }

    }

}
