/* 
 * tweak-api
 *
 * Tweak API to integrate with all the Tweak services.  You can find out more about Tweak      at <a href='https://www.tweak.com'>https://www.tweak.com</a>, #tweak.
 *
 * OpenAPI spec version: 1.0.4-alpha.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TweakApi.Api;
using TweakApi.Model;
using TweakApi.Client;
using System.Reflection;

namespace TweakApi.Test
{
    /// <summary>
    ///  Class for testing Bounds
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BoundsTests
    {
        // TODO uncomment below to declare an instance variable for Bounds
        //private Bounds instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Bounds
            //instance = new Bounds();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Bounds
        /// </summary>
        [Test]
        public void BoundsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Bounds
            //Assert.IsInstanceOfType<Bounds> (instance, "variable 'instance' is a Bounds");
        }

        /// <summary>
        /// Test the property 'Top'
        /// </summary>
        [Test]
        public void TopTest()
        {
            // TODO unit test for the property 'Top'
        }
        /// <summary>
        /// Test the property 'Bottom'
        /// </summary>
        [Test]
        public void BottomTest()
        {
            // TODO unit test for the property 'Bottom'
        }
        /// <summary>
        /// Test the property 'Left'
        /// </summary>
        [Test]
        public void LeftTest()
        {
            // TODO unit test for the property 'Left'
        }
        /// <summary>
        /// Test the property 'Right'
        /// </summary>
        [Test]
        public void RightTest()
        {
            // TODO unit test for the property 'Right'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

    }

}
