/* 
 * tweak-api
 *
 * Tweak API to integrate with all the Tweak services.  You can find out more about Tweak      at <a href='https://www.tweak.com'>https://www.tweak.com</a>, #tweak.
 *
 * OpenAPI spec version: 1.0.3-beta.5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TweakApi.Api;
using TweakApi.Model;
using TweakApi.Client;
using System.Reflection;

namespace TweakApi.Test
{
    /// <summary>
    ///  Class for testing TeamBuilderConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TeamBuilderConfigTests
    {
        // TODO uncomment below to declare an instance variable for TeamBuilderConfig
        //private TeamBuilderConfig instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TeamBuilderConfig
            //instance = new TeamBuilderConfig();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TeamBuilderConfig
        /// </summary>
        [Test]
        public void TeamBuilderConfigInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TeamBuilderConfig
            //Assert.IsInstanceOfType<TeamBuilderConfig> (instance, "variable 'instance' is a TeamBuilderConfig");
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'DebugMode'
        /// </summary>
        [Test]
        public void DebugModeTest()
        {
            // TODO unit test for the property 'DebugMode'
        }
        /// <summary>
        /// Test the property 'Features'
        /// </summary>
        [Test]
        public void FeaturesTest()
        {
            // TODO unit test for the property 'Features'
        }
        /// <summary>
        /// Test the property 'Ui'
        /// </summary>
        [Test]
        public void UiTest()
        {
            // TODO unit test for the property 'Ui'
        }
        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Test]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }
        /// <summary>
        /// Test the property 'Modified'
        /// </summary>
        [Test]
        public void ModifiedTest()
        {
            // TODO unit test for the property 'Modified'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'TeamId'
        /// </summary>
        [Test]
        public void TeamIdTest()
        {
            // TODO unit test for the property 'TeamId'
        }
        /// <summary>
        /// Test the property 'Team'
        /// </summary>
        [Test]
        public void TeamTest()
        {
            // TODO unit test for the property 'Team'
        }
        /// <summary>
        /// Test the property 'ProductGroups'
        /// </summary>
        [Test]
        public void ProductGroupsTest()
        {
            // TODO unit test for the property 'ProductGroups'
        }
        /// <summary>
        /// Test the property 'ProductTypes'
        /// </summary>
        [Test]
        public void ProductTypesTest()
        {
            // TODO unit test for the property 'ProductTypes'
        }
        /// <summary>
        /// Test the property 'ProductSizes'
        /// </summary>
        [Test]
        public void ProductSizesTest()
        {
            // TODO unit test for the property 'ProductSizes'
        }
        /// <summary>
        /// Test the property 'ProductSizeMaterials'
        /// </summary>
        [Test]
        public void ProductSizeMaterialsTest()
        {
            // TODO unit test for the property 'ProductSizeMaterials'
        }
        /// <summary>
        /// Test the property 'ProductSizeMaterialsRel'
        /// </summary>
        [Test]
        public void ProductSizeMaterialsRelTest()
        {
            // TODO unit test for the property 'ProductSizeMaterialsRel'
        }

    }

}
