/* 
 * tweak-api
 *
 * Tweak API to integrate with all the Tweak services.  You can find out more about Tweak      at <a href='https://www.tweak.com'>https://www.tweak.com</a>, #tweak.
 *
 * OpenAPI spec version: 1.0.4-alpha.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TweakApi.Api;
using TweakApi.Model;
using TweakApi.Client;
using System.Reflection;

namespace TweakApi.Test
{
    /// <summary>
    ///  Class for testing TeamPermissionSet
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TeamPermissionSetTests
    {
        // TODO uncomment below to declare an instance variable for TeamPermissionSet
        //private TeamPermissionSet instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TeamPermissionSet
            //instance = new TeamPermissionSet();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TeamPermissionSet
        /// </summary>
        [Test]
        public void TeamPermissionSetInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TeamPermissionSet
            //Assert.IsInstanceOfType<TeamPermissionSet> (instance, "variable 'instance' is a TeamPermissionSet");
        }

        /// <summary>
        /// Test the property 'EmailNotification'
        /// </summary>
        [Test]
        public void EmailNotificationTest()
        {
            // TODO unit test for the property 'EmailNotification'
        }
        /// <summary>
        /// Test the property 'TemplatePermission'
        /// </summary>
        [Test]
        public void TemplatePermissionTest()
        {
            // TODO unit test for the property 'TemplatePermission'
        }
        /// <summary>
        /// Test the property 'TweakTemplatePermission'
        /// </summary>
        [Test]
        public void TweakTemplatePermissionTest()
        {
            // TODO unit test for the property 'TweakTemplatePermission'
        }
        /// <summary>
        /// Test the property 'TeamCustomerPermission'
        /// </summary>
        [Test]
        public void TeamCustomerPermissionTest()
        {
            // TODO unit test for the property 'TeamCustomerPermission'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'TeamId'
        /// </summary>
        [Test]
        public void TeamIdTest()
        {
            // TODO unit test for the property 'TeamId'
        }
        /// <summary>
        /// Test the property 'Team'
        /// </summary>
        [Test]
        public void TeamTest()
        {
            // TODO unit test for the property 'Team'
        }

    }

}
